tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Distributed revision control system
brew "git"
cask "boostnote"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "honto"
cask "iterm2"
cask "karabiner-elements"
cask "macvim"
cask "postman"
cask "sequel-pro"
